export const DEFAULT_DAEMON_EXECUTING_RUNS = 4;
export const DEFAULT_PROJECT_EXECUTING_RUNS = 1;
export const DEFAULT_DAEMON_NEW_START_QUEUE = 1_000;
export const DEFAULT_PROJECT_NEW_START_QUEUE = 100;
export const DEFAULT_RUNNER_IDLE_MILLIS = 60_000;
export const CONTINUATION_BURST = 3;
