/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as IndexRouteImport } from './routes/index.tsx'
import { Route as RunsRouteImport } from './routes/runs.tsx'
import { Route as RunsIndexRouteImport } from './routes/runs.index.tsx'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId.tsx'
import { Route as RunsRunIdGatesGateAskingRouteImport } from './routes/runs.$runId.gates.$gate.$asking.tsx'
import { Route as RunsRunIdPhasesNameAttemptRouteImport } from './routes/runs.$runId.phases.$name.$attempt.tsx'
import { Route as RunsRunIdSandboxesNameAcquisitionRouteImport } from './routes/runs.$runId.sandboxes.$name.$acquisition.tsx'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RunsRoute,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => RunsRoute,
} as any)
const RunsRunIdGatesGateAskingRoute =
  RunsRunIdGatesGateAskingRouteImport.update({
    id: '/gates/$gate/$asking',
    path: '/gates/$gate/$asking',
    getParentRoute: () => RunsRunIdRoute,
  } as any)
const RunsRunIdPhasesNameAttemptRoute =
  RunsRunIdPhasesNameAttemptRouteImport.update({
    id: '/phases/$name/$attempt',
    path: '/phases/$name/$attempt',
    getParentRoute: () => RunsRunIdRoute,
  } as any)
const RunsRunIdSandboxesNameAcquisitionRoute =
  RunsRunIdSandboxesNameAcquisitionRouteImport.update({
    id: '/sandboxes/$name/$acquisition',
    path: '/sandboxes/$name/$acquisition',
    getParentRoute: () => RunsRunIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/runs': typeof RunsRouteWithChildren
  '/runs/$runId': typeof RunsRunIdRouteWithChildren
  '/runs/': typeof RunsIndexRoute
  '/runs/$runId/gates/$gate/$asking': typeof RunsRunIdGatesGateAskingRoute
  '/runs/$runId/phases/$name/$attempt': typeof RunsRunIdPhasesNameAttemptRoute
  '/runs/$runId/sandboxes/$name/$acquisition': typeof RunsRunIdSandboxesNameAcquisitionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/runs/$runId': typeof RunsRunIdRouteWithChildren
  '/runs': typeof RunsIndexRoute
  '/runs/$runId/gates/$gate/$asking': typeof RunsRunIdGatesGateAskingRoute
  '/runs/$runId/phases/$name/$attempt': typeof RunsRunIdPhasesNameAttemptRoute
  '/runs/$runId/sandboxes/$name/$acquisition': typeof RunsRunIdSandboxesNameAcquisitionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/runs': typeof RunsRouteWithChildren
  '/runs/$runId': typeof RunsRunIdRouteWithChildren
  '/runs/': typeof RunsIndexRoute
  '/runs/$runId/gates/$gate/$asking': typeof RunsRunIdGatesGateAskingRoute
  '/runs/$runId/phases/$name/$attempt': typeof RunsRunIdPhasesNameAttemptRoute
  '/runs/$runId/sandboxes/$name/$acquisition': typeof RunsRunIdSandboxesNameAcquisitionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/runs'
    | '/runs/$runId'
    | '/runs/'
    | '/runs/$runId/gates/$gate/$asking'
    | '/runs/$runId/phases/$name/$attempt'
    | '/runs/$runId/sandboxes/$name/$acquisition'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/runs/$runId'
    | '/runs'
    | '/runs/$runId/gates/$gate/$asking'
    | '/runs/$runId/phases/$name/$attempt'
    | '/runs/$runId/sandboxes/$name/$acquisition'
  id:
    | '__root__'
    | '/'
    | '/runs'
    | '/runs/$runId'
    | '/runs/'
    | '/runs/$runId/gates/$gate/$asking'
    | '/runs/$runId/phases/$name/$attempt'
    | '/runs/$runId/sandboxes/$name/$acquisition'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RunsRoute: typeof RunsRouteWithChildren
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof RunsRoute
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof RunsRoute
    }
    '/runs/$runId/gates/$gate/$asking': {
      id: '/runs/$runId/gates/$gate/$asking'
      path: '/gates/$gate/$asking'
      fullPath: '/runs/$runId/gates/$gate/$asking'
      preLoaderRoute: typeof RunsRunIdGatesGateAskingRouteImport
      parentRoute: typeof RunsRunIdRoute
    }
    '/runs/$runId/phases/$name/$attempt': {
      id: '/runs/$runId/phases/$name/$attempt'
      path: '/phases/$name/$attempt'
      fullPath: '/runs/$runId/phases/$name/$attempt'
      preLoaderRoute: typeof RunsRunIdPhasesNameAttemptRouteImport
      parentRoute: typeof RunsRunIdRoute
    }
    '/runs/$runId/sandboxes/$name/$acquisition': {
      id: '/runs/$runId/sandboxes/$name/$acquisition'
      path: '/sandboxes/$name/$acquisition'
      fullPath: '/runs/$runId/sandboxes/$name/$acquisition'
      preLoaderRoute: typeof RunsRunIdSandboxesNameAcquisitionRouteImport
      parentRoute: typeof RunsRunIdRoute
    }
  }
}

interface RunsRunIdRouteChildren {
  RunsRunIdGatesGateAskingRoute: typeof RunsRunIdGatesGateAskingRoute
  RunsRunIdPhasesNameAttemptRoute: typeof RunsRunIdPhasesNameAttemptRoute
  RunsRunIdSandboxesNameAcquisitionRoute: typeof RunsRunIdSandboxesNameAcquisitionRoute
}

const RunsRunIdRouteChildren: RunsRunIdRouteChildren = {
  RunsRunIdGatesGateAskingRoute: RunsRunIdGatesGateAskingRoute,
  RunsRunIdPhasesNameAttemptRoute: RunsRunIdPhasesNameAttemptRoute,
  RunsRunIdSandboxesNameAcquisitionRoute:
    RunsRunIdSandboxesNameAcquisitionRoute,
}

const RunsRunIdRouteWithChildren = RunsRunIdRoute._addFileChildren(
  RunsRunIdRouteChildren,
)

interface RunsRouteChildren {
  RunsRunIdRoute: typeof RunsRunIdRouteWithChildren
  RunsIndexRoute: typeof RunsIndexRoute
}

const RunsRouteChildren: RunsRouteChildren = {
  RunsRunIdRoute: RunsRunIdRouteWithChildren,
  RunsIndexRoute: RunsIndexRoute,
}

const RunsRouteWithChildren = RunsRoute._addFileChildren(RunsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RunsRoute: RunsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
