import type { FactoryChoices } from "../models/FactoryChoices.ts";
import { placeholder } from "../models/Placeholder.ts";
import { ownedByYou } from "./starter.ts";

/**
 * The one place a factory writes down the commands its phases run.
 *
 * **Two kinds of entry, and the difference is the whole of edge 6.** `install` is knowledge — a
 * lockfile is evidence, and `.kojo/sandbox/Dockerfile` installs the manager that lockfile named.
 * `test`, `lint` and `build` are not knowledge: no scaffolder can read a repository and know how
 * its author runs a suite. So they are stamped as commands that say out loud that they are fake,
 * print the file to edit, and exit non-zero.
 *
 * A plausible guess would be worse than this in the exact case that matters. `npm test` on a
 * repository with no test script exits 0 and prints nothing, so the mechanical half of the
 * acceptance would say the suite is clean — about a suite that was never run.
 *
 * The placeholder text is generated by `placeholder()` in the Kojo package rather than written
 * here, so `kojo doctor` can recognise a survivor without parsing anything: it is the same marker
 * on both sides.
 */
export const commands = (choices: FactoryChoices): string => {
  const evidence =
    choices.toolchain.evidence === undefined
      ? "no lockfile was found, so npm was assumed"
      : `detected from ${choices.toolchain.evidence}`;

  return [
    ...ownedByYou("Every real invocation this factory makes. Three of the four are still fake."),
    "",
    'import { isPlaceholder } from "kojo/contexts/scaffold/models/Placeholder";',
    "",
    "/**",
    " * What a code phase runs.",
    " *",
    " * `install` is real: your lockfile said which package manager this repository uses, and",
    " * `.kojo/sandbox/Dockerfile` installs the same one. Change one and change the other, or a",
    " * phase will call a tool the image does not carry.",
    " *",
    " * The other three are **placeholders**, and they are obvious on purpose. Each one prints",
    " * `KOJO-PLACEHOLDER` and exits 78, so the first run that reaches it stops and says which file",
    " * to edit. Replace them with the commands you actually run. Until you do, the mechanical half",
    " * of every acceptance refuses, which is the honest answer for a factory nobody has finished.",
    " */",
    "export const commands = {",
    `  /** Restore dependencies — ${choices.toolchain.manager}, ${evidence}. */`,
    `  install: ${JSON.stringify(choices.toolchain.install)},`,
    "",
    '  /** Your suite. Replace me — e.g. `"bun test"`, `"pytest -q"`, `"go test ./..."`. */',
    `  test: ${JSON.stringify(placeholder("test"))},`,
    "",
    "  /** Your linter. Replace me. */",
    `  lint: ${JSON.stringify(placeholder("lint"))},`,
    "",
    "  /** Your build. Replace me, or delete this entry if this repository does not build. */",
    `  build: ${JSON.stringify(placeholder("build"))},`,
    "} as const;",
    "",
    "/**",
    " * Which commands are still fake.",
    " *",
    " * `isPlaceholder` is Kojo's own, so the test is the same on both sides and nothing about the",
    " * shape of this file has to be parsed to answer it. A half-edited command that kept the marker",
    " * is still caught.",
    " */",
    "export const survivingPlaceholders = (): ReadonlyArray<string> =>",
    "  Object.entries(commands)",
    "    .filter(([, command]) => isPlaceholder(command))",
    "    .map(([name]) => name);",
    "",
  ].join("\n");
};
