// biome-ignore-all lint/suspicious/noTemplateCurlyInString: every `${…}` below belongs to the
// TypeScript this module *writes*, not to the TypeScript it *is*. Making these template literals
// would interpolate variables of this program into a stamped file that has its own.

import { defaultTrunk } from "../../shared/models/FactoryLayout.ts";
import type { FactoryChoices } from "../models/FactoryChoices.ts";
import { ownedByYou, providerSource, type Starter } from "./starter.ts";

/**
 * The lane from the design record: scout, fix, re-ask until it is right, measure, land.
 *
 * It exists beside `review` to show the one construct Kojo does **not** let an author write by
 * hand — `reviewed`. A gate inside a hand-written loop reads the first verdict back forever,
 * because a `DurableDeferred` is keyed by name and refuses to be overwritten. `reviewed` names each
 * asking from the engine's own attempt counter, which is the only counter that advances.
 */
const envelopes = [
  ...ownedByYou("The shape of every answer an agent of this factory may give."),
  "//",
  "// One declaration serves four uses: the type at the call site, the decoder, the JSON Schema the",
  "// agent is shown, and the wire contract. Kojo renders the schema into the prompt itself, so",
  "// there is never a hand-written example here to drift out of step with the decoder.",
  "",
  'import { Schema } from "effect";',
  'import { EnvelopeBase } from "kojo/contexts/workflow/models/Envelope";',
  "",
  "/** What the scout found. It changes nothing, so it claims artifacts rather than a diff. */",
  'export class Scouted extends EnvelopeBase.extend<Scouted>("Scouted")({',
  '  _tag: Schema.tag("Scouted"),',
  "  /** Where the fault lives, in the scout's own words. */",
  "  finding: Schema.String,",
  "  /** The notes the scout wrote. `checks.ts` goes and looks for each one. */",
  "  artifacts: Schema.Array(Schema.String),",
  "}) {}",
  "",
  "/** What the hotfixer changed. */",
  'export class Built extends EnvelopeBase.extend<Built>("Built")({',
  '  _tag: Schema.tag("Built"),',
  "  /** One paragraph a reviewer reads before they read the diff. */",
  "  summary: Schema.String,",
  "  /** Every path the working tree now differs on. `checks.ts` goes and looks. */",
  "  changedFiles: Schema.Array(Schema.String),",
  "}) {}",
  "",
].join("\n");

const checks = (): string =>
  [
    ...ownedByYou("Your definition of done — what an agent's answer has to survive."),
    "//",
    "// A check never asks the agent anything. It compares a claim against the repository, and it",
    "// returns faults rather than a boolean, because a correction turn is written from the fault.",
    "",
    'import type { Workspace } from "kojo/contexts/sandbox/ports/Workspace";',
    'import type { Check } from "kojo/contexts/workflow/guards/Check";',
    'import { artifactsExist } from "kojo/contexts/workflow/guards/checks/artifactsExist";',
    'import { diffMatchesClaims } from "kojo/contexts/workflow/guards/checks/diffMatchesClaims";',
    'import type { Built, Scouted } from "./envelopes.ts";',
    "",
    "/**",
    " * The scout really wrote the notes it says it wrote.",
    " *",
    " * Worth running on a phase that changes nothing: the next phase is built on these files, so a",
    " * note that is not there is a fault the whole rest of the run inherits.",
    " */",
    "export const scouted: ReadonlyArray<Check<Scouted, Workspace>> = [",
    '  artifactsExist<Scouted>({ claim: "artifacts", paths: (answer) => answer.artifacts }),',
    "];",
    "",
    "/**",
    " * The hotfixer listed exactly the paths the working tree changed.",
    " *",
    " * The envelope has to be named — `diffMatchesClaims<Built>` — because `Built` appears only in",
    " * the selector's parameter, and a bare arrow gives the compiler nothing to infer it from.",
    " */",
    "export const built: ReadonlyArray<Check<Built, Workspace>> = [",
    '  diffMatchesClaims<Built>({ claim: "changedFiles", files: (answer) => answer.changedFiles }),',
    "];",
    "",
  ].join("\n");

const workflow = (choices: FactoryChoices) => {
  const provider = providerSource(choices);

  return {
    file: "hotfix.ts",
    source: [
      ...ownedByYou("A lane: scout, fix, re-ask until it is right, measure, land."),
      "//",
      '// Start it with `kojo run hotfix "<what is broken>"`.',
      "//",
      "// Three things about the shape are worth keeping when you edit it:",
      "//",
      "//  - The `sandboxed` scope is **around** the phases, never inside one. A gate suspends the",
      "//    run by interrupting it, and an activity retries on interrupt — so a sandbox acquired",
      "//    inside a phase turns waiting for a human into a defect.",
      "//  - A loop that contains a gate must be `reviewed`, never `while` or `for`. Every other",
      "//    loop in a workflow can be plain control flow; this one cannot. See the note above",
      "//    `reviewed` in the engine for why.",
      "//  - Nothing irreversible happens outside a phase. A workflow body replays from the top on",
      "//    every resume; only a phase's recorded result is replayed instead of re-run.",
      "",
      'import { Duration, Effect, Schema } from "effect";',
      'import * as SandcastleAgentInvoker from "kojo/contexts/agent/adapters/SandcastleAgentInvoker";',
      'import { AgentInvocationError } from "kojo/contexts/agent/models/AgentInvocationError";',
      'import { RosterError } from "kojo/contexts/agent/models/RosterError";',
      'import { GateExpired } from "kojo/contexts/gate/models/GateExpired";',
      'import { GateRejected } from "kojo/contexts/gate/models/GateRejected";',
      'import { GateUnreachable } from "kojo/contexts/gate/models/GateUnreachable";',
      'import * as OnExpiry from "kojo/contexts/gate/models/OnExpiry";',
      `import { ${provider.symbol} } from "kojo/contexts/sandbox/adapters/providers";`,
      'import { SandboxError } from "kojo/contexts/sandbox/models/SandboxError";',
      'import { WorkspaceError } from "kojo/contexts/sandbox/models/WorkspaceError";',
      'import { WorkspaceUnreachable } from "kojo/contexts/sandbox/models/WorkspaceUnreachable";',
      'import { WorktreeUnusable } from "kojo/contexts/sandbox/models/WorktreeUnusable";',
      'import { Workspace } from "kojo/contexts/sandbox/ports/Workspace";',
      'import { runBranch } from "kojo/contexts/shared/models/RunBranch";',
      'import { withPermissions } from "kojo/contexts/workflow/guards/Permissions";',
      'import { Acceptance, Judgement } from "kojo/contexts/workflow/models/Acceptance";',
      'import { CheckViolation } from "kojo/contexts/workflow/models/CheckViolation";',
      'import { EnvelopeParseError } from "kojo/contexts/workflow/models/EnvelopeParseError";',
      'import { MergeRefused } from "kojo/contexts/workflow/models/MergeRefused";',
      'import { NotAccepted } from "kojo/contexts/workflow/models/NotAccepted";',
      'import { PermissionBreach } from "kojo/contexts/workflow/models/PermissionBreach";',
      'import { factoryOwnPaths } from "kojo/contexts/workflow/models/PermissionPolicy";',
      'import { CurrentRun } from "kojo/contexts/workflow/services/CurrentRun";',
      'import { agent } from "kojo/contexts/workflow/services/phase/agent";',
      'import { code } from "kojo/contexts/workflow/services/phase/code";',
      'import { merge } from "kojo/contexts/workflow/services/phase/merge";',
      'import { reviewed } from "kojo/contexts/workflow/services/reviewed";',
      'import { sandboxed } from "kojo/contexts/workflow/services/sandboxed";',
      'import { workflow } from "kojo/contexts/workflow/services/workflow";',
      'import { built as builtChecks, scouted as scoutedChecks } from "../checks.ts";',
      'import { commands } from "../commands.ts";',
      'import { Built, Scouted } from "../envelopes.ts";',
      "",
      "/** Who is asked. The name reaches the asking, so it must be a name a person answers to. */",
      'const actor = "engineer";',
      "",
      "/**",
      " * The branch an accepted run lands on. **Change it if your trunk is not called `main`.**",
      " *",
      " * The merge is performed on the repository you started the run from, so `kojo run` has to be",
      " * launched while that repository is checked out on this branch and has nothing uncommitted in",
      " * it. Anything else and the merge refuses by name — it says which branch it found and which",
      " * one it wanted — rather than landing the work somewhere nobody expected it.",
      " */",
      `const trunk = "${defaultTrunk}";`,
      "",
      "/**",
      " * Where the work runs.",
      " *",
      " * Built per run rather than held as a module constant, because a provider is the only place a",
      " * run's own environment can be attached — `CreateSandboxOptions` carries no `env`.",
      " */",
      `const provider = () => ${provider.expression};`,
      "",
      "/**",
      " * Who actually gets called, and where.",
      " *",
      " * Provided **inside** the sandbox scope, because an agent runs in the container the phase is",
      " * standing in and the invoker therefore has to hold that container. The roster is",
      " * `.kojo/kojo.config.yaml`; it is decoded and its prompt files are read while this layer is",
      " * built, so a typo in it fails naming the file before anything spawns.",
      " */",
      'const agents = SandcastleAgentInvoker.fromConfig({ config: ".kojo/kojo.config.yaml" });',
      "",
      "/**",
      " * What an agent of this factory is allowed to touch, and what it is not.",
      " *",
      " * A tool allowlist is a capability list, not a boundary: a shell runs anything, including a",
      " * `git checkout` over the very files the answer is about to be graded by. So this is verified",
      " * after the fact, against the repository \u2014 the change-set is fingerprinted before the call and",
      " * compared afterwards, and anything outside the scope is undone and fails the run.",
      " *",
      " * `factoryOwnPaths` is the roster, the workflows, the envelopes, the checks, the commands and",
      " * the prompts. An agent that can edit those can edit its own grader \u2014 and the mechanical half",
      " * of this workflow is `commands.test`, so an unguarded hotfixer can make its own suite pass.",
      " */",
      "const mayNotTouchTheFactory = (who: string) => ({",
      "  agent: who,",
      '  // `Unrestricted` means "anything the protected paths do not bar", which is the right',
      "  // setting for an agent that writes code. The scout is the interesting one: it is told to",
      "  // change nothing, and the strict reading of that is",
      '  // `writes: { _tag: "LimitedTo", patterns: [] }` \u2014 read-only \u2014 with the paths it records',
      "  // its findings on listed in `alwaysWritable`. Set it that way once you have decided where",
      "  // your scout keeps its notes; until then the guard below is the half that matters, because",
      "  // it is the half that stops an agent editing the files that grade it.",
      '  writes: { _tag: "Unrestricted" } as const,',
      "  protectedPaths: factoryOwnPaths,",
      "  alwaysWritable: [] as ReadonlyArray<string>,",
      "});",
      "",
      "/** Every way this workflow can fail. The engine persists it, so it has to be a schema. */",
      "const failures = Schema.Union([",
      "  AgentInvocationError,",
      "  CheckViolation,",
      "  EnvelopeParseError,",
      "  GateExpired,",
      "  GateRejected,",
      "  GateUnreachable,",
      "  MergeRefused,",
      "  NotAccepted,",
      "  PermissionBreach,",
      "  RosterError,",
      "  SandboxError,",
      "  WorkspaceError,",
      "  WorkspaceUnreachable,",
      "  WorktreeUnusable,",
      "]);",
      "",
      "/**",
      " * **The branch is the durable state of a run, so the work has to be on it.**",
      " *",
      " * This phase is not tidiness and it is not optional, and this workflow needs it more than once.",
      " * Every asking of the gate below suspends the run: the container is torn down while the human",
      " * thinks, and the worktree goes with it \u2014 except that Sandcastle *keeps* a dirty worktree",
      " * rather than deleting it, and the rebuild on the answer then refuses that worktree as",
      ' * `WorktreeUnusable{fault: "modified"}`. So an uncommitted change does not merely fail to',
      " * survive the gate; it stops the run being resumable at all. Measured against a real agent on",
      " * ticket 15, on the `review` template, which is the first run that ever reached such a line with",
      " * work in the tree.",
      " *",
      " * `what` is part of the phase name because a phase name is an activity key: the fix and each",
      " * revision are different pieces of work and must not share a slot.",
      " *",
      " * The message is the agent's own summary and everything else is code's \u2014 agents propose, code",
      " * disposes. The identity is the repository's own: a linked worktree shares `.git/config`, so a",
      " * repository that knows who it is commits as itself.",
      " */",
      "const commit = (what: string, summary: string) =>",
      "  code(",
      "    {",
      "      name: `commit-${what}`,",
      "      description: `Put the ${what} on this run's own branch`,",
      "      success: Schema.String,",
      "      error: WorkspaceError,",
      "    },",
      "    Effect.gen(function* () {",
      "      const workspace = yield* Workspace;",
      '      yield* workspace.git(["add", "--all"]);',
      '      const staged = yield* workspace.git(["diff", "--cached", "--name-only"]);',
      "      const files = staged.stdout.trim();",
      '      if (files === "") return "the agent changed nothing, so nothing was committed";',
      '      yield* workspace.git(["commit", "--quiet", "--message", summary]);',
      '      return files.split("\\n").join(", ");',
      "    }),",
      "  );",
      "",
      "export const hotfix = workflow(",
      "  {",
      '    name: "hotfix",',
      "    payload: { fault: Schema.String },",
      "    success: Schema.String,",
      "    error: failures,",
      "    // What a run is deduplicated by. Two triggers naming one unit of work must not open two",
      "    // runs, and this string is what the engine hashes into the run id.",
      "    idempotencyKey: (payload) => `hotfix/${payload.fault}`,",
      "  },",
      "  (payload) =>",
      "    Effect.gen(function* () {",
      "      /**",
      "       * **The run names its own branch, and nothing tells it what to call it.**",
      "       *",
      "       * `runBranch` is a function of the run id and of nothing else, so a resumed run in another",
      "       * process two days later derives the same name from the same run without carrying it. It",
      "       * is also what lets `merge` below refuse to land any other branch, and what makes a failed",
      "       * run's report name a branch that is really there.",
      "       */",
      "      const run = yield* CurrentRun;",
      "      const branch = runBranch(run.runId);",
      "",
      "      const judged = yield* sandboxed(",
      '        { name: "hotfix", branch, provider: provider() },',
      "        Effect.gen(function* () {",
      "          // The scout is told to change nothing. This is what makes that an enforced rule",
      "          // rather than a sentence in a prompt file: an instruction no code checks is a",
      "          // request, and the whole point of the guard is that a request is not a boundary.",
      "          const scouted = (yield* withPermissions(",
      '            mayNotTouchTheFactory("scout"),',
      "            agent({",
      '              name: "scout",',
      '              description: "Find where the fault lives; change nothing",',
      '              agent: "scout",',
      "              prompt: payload.fault,",
      "              envelope: Scouted,",
      "              checks: scoutedChecks,",
      "            }),",
      "          )).value;",
      "",
      "          // `withPermissions` fingerprints the change-set, runs the phase, and compares. A path",
      "          // outside the policy is undone and the run fails with a `PermissionBreach` naming",
      "          // every path and what became of it \u2014 a breach is not something a re-prompt can fix,",
      "          // because the write already happened.",
      "          const first = (yield* withPermissions(",
      '            mayNotTouchTheFactory("hotfixer"),',
      "            agent({",
      '              name: "fix",',
      '              description: "Write the smallest change that resolves the fault",',
      '              agent: "hotfixer",',
      "              prompt: `${payload.fault}\\n\\nThe scout reported: ${scouted.finding}`,",
      "              envelope: Built,",
      "              checks: builtChecks,",
      "            }),",
      "          )).value;",
      "",
      '          yield* commit("fix", first.summary);',
      "",
      "          // A rejected fix goes back to the same agent, in the same conversation, and the run",
      "          // suspends on every asking — container released, branch retained. `limit` bounds it,",
      "          // and spending the bound fails with the last reviewer's own words.",
      "          const approved = yield* reviewed({",
      '            name: "approve",',
      '            description: "Does this fix land?",',
      "            actor,",
      "            limit: 3,",
      "            deadline: Duration.days(2),",
      "            onExpiry: OnExpiry.fail(),",
      "            subject: first,",
      "            // Read again on every asking, so the second reviewer sees the *revised* fix rather",
      "            // than the diff they already rejected.",
      '            context: (fix) => ({ summary: fix.summary, files: fix.changedFiles.join(", ") }),',
      "            revise: (verdict, fix) =>",
      "              Effect.gen(function* () {",
      "                const revised = (yield* withPermissions(",
      '                  mayNotTouchTheFactory("hotfixer"),',
      "                  agent({",
      '                    name: "revise",',
      '                    description: "Address the reviewer\'s objection",',
      '                    agent: "hotfixer",',
      "                    prompt: verdict.reason,",
      "                    envelope: Built,",
      "                    checks: builtChecks,",
      "                    // `session` is what would make a revision one message rather than a cold",
      "                    // start: pass `Option.some(id)` and the agent re-enters the same",
      "                    // conversation, carrying everything it already knows. Give `Built` a field",
      "                    // for the session the invoker returned, and thread it through here.",
      "                  }),",
      "                )).value;",
      "",
      "                // The loop suspends again the moment this returns, so a revision has to reach",
      "                // the branch for the same reason the first fix did. `reviewed` keys the phases",
      "                // inside it by asking, so this is a fresh commit each round rather than a replay",
      "                // of the first one.",
      '                yield* commit("revision", revised.summary);',
      "                return revised;",
      "              }),",
      "          });",
      "",
      "          // The mechanical half of the acceptance. Note it does **not** fail when the suite is",
      "          // red: the phase did its job, and a red suite is an answer.",
      "          const mechanical = yield* code(",
      "            {",
      '              name: "verify",',
      '              description: "Run the suite over the approved fix",',
      "              success: Judgement,",
      "              error: WorkspaceError,",
      "            },",
      "            Effect.gen(function* () {",
      "              const workspace = yield* Workspace;",
      '              const ran = yield* workspace.exec(["sh", "-c", commands.test]);',
      "              return new Judgement({",
      '                by: "the suite",',
      "                accepted: ran.succeeded,",
      "                reason: ran.succeeded",
      '                  ? "the suite came back clean"',
      "                  : `exit ${ran.exitCode}: ${(ran.stderr || ran.stdout).trim().slice(-500)}`,",
      "              });",
      "            }),",
      "          );",
      "",
      "          return { summary: approved.summary, mechanical };",
      "          // The invoker goes on the *inside* of the sandbox scope. See `agents` above.",
      "        }).pipe(Effect.provide(agents)),",
      "      );",
      "",
      "      /**",
      "       * **The step everything else was for: the accepted fix lands on the trunk.**",
      "       *",
      "       * Three things about this line are the design rather than a choice:",
      "       *",
      "       *  - **Acceptance is the single condition it hangs on.** Both halves, or nothing merges:",
      "       *    the run fails with `NotAccepted`, the trunk is untouched, and the branch above is",
      "       *    left exactly as it is for whoever comes to look. A freshly stamped factory is refused",
      "       *    here on purpose, because `commands.test` is a placeholder until you write the real",
      '       *    one. "Every phase succeeded" is not that condition and cannot be made into it — a',
      "       *    `verify` phase that ran a red suite succeeded.",
      "       *  - **It is a code phase, and an agent never runs it.** Merging is a known invocation and",
      "       *    it is irreversible, so it is the last thing in a run that should depend on a",
      "       *    judgement call. The engine will not let you hand it to an agent: it takes an",
      "       *    `Acceptance`, and only a gate and a measurement produce one.",
      "       *  - **It is outside the sandbox scope, on purpose.** Inside, the workspace is the worktree",
      "       *    this run's branch is checked out in, and merging the branch there would be merging a",
      "       *    branch into itself. Out here the workspace is the repository you started the run from.",
      "       *    Setup before, risk inside, merge after.",
      "       */",
      "      const landed = yield* merge({",
      "        into: trunk,",
      "        acceptance: new Acceptance({",
      "          mechanical: judged.mechanical,",
      "          // `reviewed` only returns when somebody approved, so reaching this line is the human",
      "          // half. It carries no reason because there is no refusal to explain.",
      '          human: new Judgement({ by: actor, accepted: true, reason: "" }),',
      "        }),",
      "      });",
      "",
      "      return `${judged.summary}\\n\\nLanded ${landed.branch} on ${landed.into} as ${landed.sha}.`;",
      "    }),",
      ");",
      "",
    ].join("\n"),
  };
};

export const hotfix: Starter = {
  name: "hotfix",
  summary: "Scout, fix, re-ask until it is right, measure, land. Shows the reviewed loop.",
  agents: [
    {
      name: "scout",
      purpose: "Find where the fault lives and write it down; change nothing",
      tools: [],
      system: [
        "# The scout",
        "",
        "You investigate. You do not fix anything, and you do not change any file that is part of",
        "the product — the only files you write are the notes you report.",
        "",
        "How you are judged:",
        "",
        "- Your answer is decoded against a schema. An answer that does not decode is sent back to",
        "  you once, with the decoder's own complaint, and then the phase fails.",
        "- Every note you claim to have written is looked for on disk. A note that is not there is a",
        "  fault, whatever the rest of the answer says.",
        "",
        "The agent after you reads only your finding and your notes. Write them for that reader.",
        "",
      ].join("\n"),
      user: [
        "Find where the fault described below lives.",
        "",
        "Read the code. Write your notes to files, and report the path of every note you wrote and",
        "one sentence naming where the fault is.",
        "",
      ].join("\n"),
    },
    {
      name: "hotfixer",
      purpose: "Write the smallest change that resolves the fault",
      tools: [],
      system: [
        "# The hotfixer",
        "",
        "You write the smallest change that resolves one fault. A human reviews your answer and may",
        "send it back with an objection; when they do, you get their words and the same conversation.",
        "",
        "How you are judged:",
        "",
        "- Your answer is decoded against a schema. An answer that does not decode is sent back to",
        "  you once, with the decoder's own complaint, and then the phase fails.",
        "- Every path you list is checked against the working tree. A path you list and did not",
        "  change is a fault, and so is a path you changed and did not list.",
        "- A human reads your summary before they read the diff. Write it for them.",
        "",
        "Do not reformat what you did not come here to change, and do not fix a second fault you",
        "noticed on the way. A change nobody asked for is a change nobody reviewed.",
        "",
      ].join("\n"),
      user: [
        "Resolve the fault described below.",
        "",
        "Make the change, then list every path whose content now differs and summarise what you did",
        "in one paragraph.",
        "",
      ].join("\n"),
    },
  ],
  envelopes,
  checks,
  workflow,
};
