// biome-ignore-all lint/suspicious/noTemplateCurlyInString: every `${…}` below belongs to the
// TypeScript this module *writes*, not to the TypeScript it *is*. Making these template literals
// would interpolate variables of this program into a stamped file that has its own.

import { defaultTrunk } from "../../shared/models/FactoryLayout.ts";
import type { FactoryChoices } from "../models/FactoryChoices.ts";
import { ownedByYou, providerSource, type Starter } from "./starter.ts";

/**
 * The smallest factory that is still a whole factory.
 *
 * One agent writes, the suite judges, a human judges, and the two judgements are combined into the
 * single `Acceptance` that anything irreversible hangs on. It is deliberately linear: it holds no
 * loop, so nothing here needs `reviewed`, and an author can read it top to bottom in a minute.
 */
const envelopes = [
  ...ownedByYou("The shape of every answer an agent of this factory may give."),
  "//",
  "// One declaration serves four uses: the type at the call site, the decoder, the JSON Schema the",
  "// agent is shown, and the wire contract. Kojo renders the schema into the prompt itself, so",
  "// there is never a hand-written example here to drift out of step with the decoder.",
  "",
  'import { Schema } from "effect";',
  'import { EnvelopeBase } from "@carere/kojo/contexts/workflow/models/Envelope";',
  "",
  "/** What the drafter hands back: what it did, and every path it touched. */",
  'export class Drafted extends EnvelopeBase.extend<Drafted>("Drafted")({',
  '  _tag: Schema.tag("Drafted"),',
  "  /** One paragraph a reviewer reads before they read the diff. */",
  "  summary: Schema.String,",
  "  /** Every path the working tree now differs on. `checks.ts` goes and looks. */",
  "  files: Schema.Array(Schema.String),",
  "}) {}",
  "",
].join("\n");

const checks = (): string =>
  [
    ...ownedByYou("Your definition of done — what an agent's answer has to survive."),
    "//",
    "// A check never asks the agent anything. It compares a claim against the repository, and it",
    "// returns faults rather than a boolean, because a correction turn is written from the fault.",
    "",
    'import { diffMatchesClaims } from "@carere/kojo/contexts/workflow/guards/checks/diffMatchesClaims";',
    'import type { Check } from "@carere/kojo/contexts/workflow/guards/Check";',
    'import type { Workspace } from "@carere/kojo/contexts/sandbox/ports/Workspace";',
    'import type { Drafted } from "./envelopes.ts";',
    "",
    "/**",
    " * The drafter listed exactly the paths the working tree changed.",
    " *",
    " * Both directions are faults: a path claimed and unchanged is work that was not done, and a",
    " * path changed and unclaimed is work a reviewer would approve without having read it.",
    " *",
    " * The envelope has to be named — `diffMatchesClaims<Drafted>` — because `Drafted` appears only",
    " * in the selector's parameter, and a bare arrow gives the compiler nothing to infer it from.",
    " */",
    "export const drafted: ReadonlyArray<Check<Drafted, Workspace>> = [",
    '  diffMatchesClaims<Drafted>({ claim: "files", files: (answer) => answer.files }),',
    "];",
    "",
  ].join("\n");

const workflow = (choices: FactoryChoices) => {
  const provider = providerSource(choices);

  return {
    file: "review.ts",
    source: [
      ...ownedByYou("A workflow: draft, measure, ask, land. This is the product."),
      "//",
      '// Start it with `kojo run review "<what the change is>"`.',
      "//",
      "// Two things about the shape are worth keeping when you edit it:",
      "//",
      "//  - The `sandboxed` scope is **around** the phases, never inside one. A gate suspends the",
      "//    run by interrupting it, and an activity retries on interrupt — so a sandbox acquired",
      "//    inside a phase turns waiting for a human into a defect. Around the phases, the",
      "//    container is torn down while the human thinks and rebuilt from the branch afterwards.",
      "//  - Nothing irreversible happens outside a phase. A workflow body replays from the top on",
      "//    every resume; only a phase's recorded result is replayed instead of re-run.",
      "",
      'import { Duration, Effect, Schema } from "effect";',
      'import * as SandcastleAgentInvoker from "@carere/kojo/contexts/agent/adapters/SandcastleAgentInvoker";',
      'import { AgentInvocationError } from "@carere/kojo/contexts/agent/models/AgentInvocationError";',
      'import { RosterError } from "@carere/kojo/contexts/agent/models/RosterError";',
      'import { GateExpired } from "@carere/kojo/contexts/gate/models/GateExpired";',
      'import { GateUnreachable } from "@carere/kojo/contexts/gate/models/GateUnreachable";',
      'import * as OnExpiry from "@carere/kojo/contexts/gate/models/OnExpiry";',
      `import { ${provider.symbol} } from "@carere/kojo/contexts/sandbox/adapters/providers";`,
      'import { SandboxError } from "@carere/kojo/contexts/sandbox/models/SandboxError";',
      'import { WorkspaceError } from "@carere/kojo/contexts/sandbox/models/WorkspaceError";',
      'import { WorkspaceUnreachable } from "@carere/kojo/contexts/sandbox/models/WorkspaceUnreachable";',
      'import { WorktreeUnusable } from "@carere/kojo/contexts/sandbox/models/WorktreeUnusable";',
      'import { Workspace } from "@carere/kojo/contexts/sandbox/ports/Workspace";',
      'import { runBranch } from "@carere/kojo/contexts/shared/models/RunBranch";',
      'import { withPermissions } from "@carere/kojo/contexts/workflow/guards/Permissions";',
      'import { Acceptance, Judgement } from "@carere/kojo/contexts/workflow/models/Acceptance";',
      'import { CheckViolation } from "@carere/kojo/contexts/workflow/models/CheckViolation";',
      'import { EnvelopeParseError } from "@carere/kojo/contexts/workflow/models/EnvelopeParseError";',
      'import { MergeRefused } from "@carere/kojo/contexts/workflow/models/MergeRefused";',
      'import { NotAccepted } from "@carere/kojo/contexts/workflow/models/NotAccepted";',
      'import { PermissionBreach } from "@carere/kojo/contexts/workflow/models/PermissionBreach";',
      'import { factoryOwnPaths } from "@carere/kojo/contexts/workflow/models/PermissionPolicy";',
      'import { fromVerdict } from "@carere/kojo/contexts/workflow/services/acceptance";',
      'import { CurrentRun } from "@carere/kojo/contexts/workflow/services/CurrentRun";',
      'import { agent } from "@carere/kojo/contexts/workflow/services/phase/agent";',
      'import { code } from "@carere/kojo/contexts/workflow/services/phase/code";',
      'import { gate } from "@carere/kojo/contexts/workflow/services/phase/gate";',
      'import { merge } from "@carere/kojo/contexts/workflow/services/phase/merge";',
      'import { sandboxed } from "@carere/kojo/contexts/workflow/services/sandboxed";',
      'import { workflow } from "@carere/kojo/contexts/workflow/services/workflow";',
      'import { drafted as draftedChecks } from "../checks.ts";',
      'import { commands } from "../commands.ts";',
      'import { Drafted } from "../envelopes.ts";',
      "",
      "/** Who is asked. The name reaches the asking, so it must be a name a person answers to. */",
      'const actor = "engineer";',
      "",
      "/**",
      " * The branch an accepted run lands on. **Change it if your trunk is not called `main`.**",
      " *",
      " * The merge is performed on the repository you started the run from, so `kojo run` has to be",
      " * launched while that repository is checked out on this branch and has nothing uncommitted in",
      " * it. Anything else and the merge refuses by name — it says which branch it found and which",
      " * one it wanted — rather than landing the work somewhere nobody expected it.",
      " */",
      `const trunk = "${defaultTrunk}";`,
      "",
      "/**",
      " * Where the work runs.",
      " *",
      " * Built per run rather than held as a module constant, because a provider is the only place a",
      " * run's own environment can be attached — `CreateSandboxOptions` carries no `env`.",
      " */",
      `const provider = () => ${provider.expression};`,
      "",
      "/**",
      " * Who actually gets called, and where.",
      " *",
      " * **It is provided inside the sandbox scope, not outside it.** An agent runs in the container",
      " * the phase is standing in, so the invoker has to hold that container — which means the layer",
      " * is built where one exists. Provided at the top instead, there would be nothing to hold, and",
      " * the build that assembles this factory wires `AbsentAgentInvoker` there on purpose: it",
      " * refuses every call and says why, rather than dying on a missing service.",
      " *",
      " * The roster is `.kojo/kojo.config.yaml` beside this file. It is decoded, and every agent's",
      " * `prompts/<name>/{system,user}.md` is read, while this layer is being built — so a factory",
      " * with a typo in its roster fails naming the file, before anything spawns.",
      " */",
      'const agents = SandcastleAgentInvoker.fromConfig({ config: ".kojo/kojo.config.yaml" });',
      "",
      "/**",
      " * What the drafter is allowed to leave behind.",
      " *",
      " * A tool allowlist is a capability list, not a boundary: a shell runs anything, including a",
      " * `git checkout` over the very files the answer is about to be graded by. So this is verified",
      " * after the fact, against the repository — the change-set is fingerprinted before the call and",
      " * compared afterwards, and anything outside the scope is undone and fails the run.",
      " *",
      " * `factoryOwnPaths` is the roster, the workflows, the envelopes, the checks, the commands and",
      " * the prompts. An agent that can edit those can edit its own grader.",
      " */",
      "const drafterMay = {",
      '  agent: "drafter",',
      '  writes: { _tag: "Unrestricted" } as const,',
      "  protectedPaths: factoryOwnPaths,",
      "  alwaysWritable: [] as ReadonlyArray<string>,",
      "};",
      "",
      "/** Every way this workflow can fail. The engine persists it, so it has to be a schema. */",
      "const failures = Schema.Union([",
      "  AgentInvocationError,",
      "  CheckViolation,",
      "  EnvelopeParseError,",
      "  GateExpired,",
      "  GateUnreachable,",
      "  MergeRefused,",
      "  NotAccepted,",
      "  PermissionBreach,",
      "  RosterError,",
      "  SandboxError,",
      "  WorkspaceError,",
      "  WorkspaceUnreachable,",
      "  WorktreeUnusable,",
      "]);",
      "",
      "export const review = workflow(",
      "  {",
      '    name: "review",',
      "    payload: { subject: Schema.String },",
      "    success: Schema.String,",
      "    error: failures,",
      "    // What a run is deduplicated by. Two triggers naming one unit of work must not open two",
      "    // runs, and this string is what the engine hashes into the run id.",
      "    idempotencyKey: (payload) => `review/${payload.subject}`,",
      "  },",
      "  (payload) =>",
      "    Effect.gen(function* () {",
      "      /**",
      "       * **The run names its own branch, and nothing tells it what to call it.**",
      "       *",
      "       * `runBranch` is a function of the run id and of nothing else, so a resumed run in another",
      "       * process two days later derives the same name from the same run without carrying it. That",
      "       * is also what lets `commit` and `merge` refuse to act on any other branch: an author",
      "       * cannot land a run's work somewhere the run does not own, and a failed run's report names",
      "       * a branch that is really there.",
      "       */",
      "      const run = yield* CurrentRun;",
      "      const branch = runBranch(run.runId);",
      "",
      "      const judged = yield* sandboxed(",
      '        { name: "review", branch, provider: provider() },',
      "        Effect.gen(function* () {",
      "          // `withPermissions` fingerprints the change-set, runs the phase, and compares. A path",
      "          // outside `drafterMay` is undone and the run fails with a `PermissionBreach` naming",
      "          // every path and what became of it — a breach is not something a re-prompt can fix,",
      "          // because the write already happened.",
      "          const drafted = yield* withPermissions(",
      "            drafterMay,",
      "            agent({",
      '              name: "draft",',
      '              description: "Make the change this run is about",',
      '              agent: "drafter",',
      "              prompt: payload.subject,",
      "              envelope: Drafted,",
      "              checks: draftedChecks,",
      "              // One repair turn. The knob is spelled out here rather than left to its default",
      "              // because bounding what an agent may spend is a decision every factory has to",
      "              // make, and this is where you find out it exists. Raise it if your envelope is",
      "              // large; lower it to 0 to refuse corrections outright.",
      "              corrections: 1,",
      "            }),",
      "          );",
      "          const answer = drafted.value;",
      "",
      "          /**",
      "           * **The branch is the durable state of a run, so the work has to be on it.**",
      "           *",
      "           * This phase is not tidiness and it is not optional. The gate below suspends the run:",
      "           * the container is torn down while the human thinks, and the worktree goes with it —",
      "           * except that Sandcastle *keeps* a dirty worktree rather than deleting it, and the",
      "           * rebuild on the answer then refuses that worktree as",
      '           * `WorktreeUnusable{fault: "modified"}`. So an uncommitted change does not merely fail',
      "           * to survive the gate; it stops the run being resumable at all. Measured against a real",
      "           * agent on ticket 15, which is the first run that ever reached this line with work in",
      "           * the tree.",
      "           *",
      "           * It is also what the merge below lands. A run whose work never reached the branch has",
      "           * nothing to land, and `--no-ff` would put an empty merge commit on your trunk.",
      "           *",
      "           * The message is the agent's own summary and everything else is code's — agents",
      "           * propose, code disposes. The identity is the repository's own: a linked worktree",
      "           * shares `.git/config`, so a repository that knows who it is commits as itself.",
      "           */",
      "          yield* code(",
      "            {",
      '              name: "commit",',
      '              description: "Put what the agent wrote on this run\'s own branch",',
      "              success: Schema.String,",
      "              error: WorkspaceError,",
      "            },",
      "            Effect.gen(function* () {",
      "              const workspace = yield* Workspace;",
      '              yield* workspace.git(["add", "--all"]);',
      '              const staged = yield* workspace.git(["diff", "--cached", "--name-only"]);',
      "              const files = staged.stdout.trim();",
      '              if (files === "") return "the agent changed nothing, so nothing was committed";',
      '              yield* workspace.git(["commit", "--quiet", "--message", answer.summary]);',
      '              return files.split("\\n").join(", ");',
      "            }),",
      "          );",
      "",
      "          // The mechanical half of the acceptance. Note it does **not** fail when a command is",
      "          // red: the phase did its job, and a red suite is an answer. Failing here would hide",
      "          // the result from the reviewer, who is the one who has to decide what to do about it.",
      "          //",
      "          // All three commands, through the `Workspace` port, so they run where the agent wrote",
      "          // — in the container on a container provider, in the worktree on this machine. Calling",
      "          // a shell directly would grade the repository you are sitting in instead.",
      "          //",
      "          // Delete a line here if you delete the matching entry from `commands.ts`.",
      "          const mechanical = yield* code(",
      "            {",
      '              name: "verify",',
      '              description: "Run this factory\'s own test, lint and build over what the agent wrote",',
      "              success: Judgement,",
      "              error: WorkspaceError,",
      "            },",
      "            Effect.gen(function* () {",
      "              const workspace = yield* Workspace;",
      "              const stages = [",
      '                ["test", commands.test],',
      '                ["lint", commands.lint],',
      '                ["build", commands.build],',
      "              ] as const;",
      "",
      "              const refused: Array<string> = [];",
      "              for (const [what, command] of stages) {",
      '                const ran = yield* workspace.exec(["sh", "-c", command]);',
      "                if (!ran.succeeded) {",
      "                  refused.push(",
      "                    `${what} exited ${ran.exitCode}: ${(ran.stderr || ran.stdout).trim().slice(-300)}`,",
      "                  );",
      "                }",
      "              }",
      "",
      "              return new Judgement({",
      '                by: "test, lint and build",',
      "                accepted: refused.length === 0,",
      "                reason:",
      "                  refused.length === 0",
      '                    ? "test, lint and build all came back clean"',
      '                    : refused.join(" · "),',
      "              });",
      "            }),",
      "          );",
      "",
      "          // The run stops here. The container is released, the branch stays, and the process",
      "          // that started the run is free to exit — `kojo gate answer` resumes it days later.",
      "          const verdict = yield* gate({",
      '            name: "approve",',
      '            description: `Land "${payload.subject}"? The suite says: ${mechanical.reason}`,',
      "            actor,",
      '            choices: ["approve", "reject"],',
      "            deadline: Duration.days(2),",
      "            onExpiry: OnExpiry.fail(),",
      "          });",
      "",
      "          return { summary: answer.summary, mechanical, verdict };",
      "          // The invoker goes on the *inside* of the sandbox scope, because that is where a",
      "          // sandbox exists. See `agents` above.",
      "        }).pipe(Effect.provide(agents)),",
      "      );",
      "",
      "      /**",
      "       * **The step everything else was for: the accepted work lands on the trunk.**",
      "       *",
      "       * Three things about this line are the design rather than a choice, and each has a way of",
      "       * being wrong that only shows up in a repository somebody cares about:",
      "       *",
      "       *  - **Acceptance is the single condition it hangs on.** `merge` takes an `Acceptance` —",
      "       *    the conjunction of the suite's verdict and the human's — and checks it before a single",
      "       *    git command runs. A rejected run, or a red suite, therefore merges *nothing*: the run",
      "       *    fails with `NotAccepted`, the trunk is untouched, and the branch above is left exactly",
      '       *    as it is for whoever comes to look. "Every phase succeeded" is not that condition and',
      "       *    cannot be made into it — a `verify` phase that ran a red suite succeeded.",
      "       *  - **It is a code phase, and an agent never runs it.** Merging is a known invocation and",
      "       *    it is irreversible, so it is the last thing in a run that should depend on a",
      "       *    judgement call. The engine will not let you hand it to one: it takes an `Acceptance`,",
      "       *    and only a gate and a measurement produce one.",
      "       *  - **It is outside the sandbox scope, on purpose.** Inside, the workspace is the worktree",
      "       *    this run's branch is checked out in, and merging the branch there would be merging a",
      "       *    branch into itself. Out here the workspace is the repository you started the run from.",
      "       *    Setup before, risk inside, merge after.",
      "       */",
      "      const landed = yield* merge({",
      "        into: trunk,",
      "        acceptance: new Acceptance({",
      "          mechanical: judged.mechanical,",
      "          // A freshly stamped factory is refused here on purpose: `commands.test` is a",
      "          // placeholder until you write the real one, so the mechanical half says no and no",
      "          // approval can outvote it.",
      "          human: fromVerdict(judged.verdict),",
      "        }),",
      "      });",
      "",
      "      return `${judged.summary}\\n\\nLanded ${landed.branch} on ${landed.into} as ${landed.sha}.`;",
      "    }),",
      ");",
      "",
    ].join("\n"),
  };
};

export const review: Starter = {
  name: "review",
  summary: "One agent, one suite, one human. The smallest factory that still waits on somebody.",
  agents: [
    {
      name: "drafter",
      purpose: "Make the change the run is about, and say exactly which files it touched",
      tools: [],
      system: [
        "# The drafter",
        "",
        "You make one change to this repository. You are one phase of a factory, not a session:",
        "there is no conversation after this answer, and nothing you say outside the answer is read.",
        "",
        "How you are judged:",
        "",
        "- Your answer is decoded against a schema. An answer that does not decode is sent back to",
        "  you once, with the decoder's own complaint, and then the phase fails.",
        "- Every path you list is checked against the working tree. A path you list and did not",
        "  change is a fault, and so is a path you changed and did not list.",
        "- A human reads your summary before they read the diff. Write it for them.",
        "",
        "Change the smallest number of files that does the job. Do not reformat what you did not",
        "come here to change.",
        "",
      ].join("\n"),
      user: [
        "Make the change described below.",
        "",
        "Work in the repository you are standing in. When you are finished, list every path whose",
        "content now differs, and summarise what you did in one paragraph.",
        "",
      ].join("\n"),
    },
  ],
  envelopes,
  checks,
  workflow,
};
