$schema: ../cache/schemas/tasks.json

fileGroups:
  configs:
    - "moon.yml"
    - "package.json"
    - "tsconfig.json"
    - "biome.json"
    - "*.config.{js,ts,cjs,mjs,mts}"
  sources:
    - "src/**/*"
  tests:
    - "tests/**/*"
    - "**/*.{test,spec}.{ts,tsx}"
  workspace:
    - "/.moon/tasks/**/*"
    - "/.moon/toolchains.yml"
    - "/.moon/workspace.yml"
    - "/.prototools"
    - "/biome.json"
    - "/bun.lock"
    - "/package.json"
    - "/tsconfig.base.json"
    - "/tsconfig.json"

implicitInputs:
  - "/.moon/tasks/**/*"
  - "/.moon/toolchains.yml"
  - "/.moon/workspace.yml"
  - "/.prototools"
  - "/biome.json"
  - "/bun.lock"
  - "/package.json"
  - "/tsconfig.base.json"
  - "/tsconfig.json"

tasks:
  check:
    command: "biome check --no-errors-on-unmatched ."

  fix:
    command: "biome check --write --no-errors-on-unmatched ."

  tsc:
    command: "tsc --build --verbose"

