import type { DaemonPaths } from "../models/DaemonPaths.ts";

const unitValue = (value: string): string =>
  `"${value.replaceAll("%", "%%").replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;

const environment = (name: string, value: string): string =>
  `Environment=${unitValue(`${name}=${value}`)}`;

const pathValue = (value: string): string =>
  [...value]
    .map((character) => {
      if (character === "%") return "%%";
      const code = character.codePointAt(0) ?? 0;
      if (code <= 0x20 || code === 0x22 || code === 0x27 || code === 0x5c || code === 0x7f) {
        return `\\x${code.toString(16).padStart(2, "0")}`;
      }
      return character;
    })
    .join("");

export const systemdUnitDocument = (
  paths: DaemonPaths,
  options: { readonly home?: string; readonly managedDirectoryName?: string } = {},
): string => {
  const managedDirectoryName = options.managedDirectoryName ?? "kojo";
  return `# Managed by Kojo. Do not edit this file.
[Unit]
Description=Kojo per-user Daemon
StartLimitIntervalSec=30s
StartLimitBurst=5

[Service]
Type=exec
ExecStart=${unitValue(paths.managedLauncher)}
WorkingDirectory=${pathValue(paths.installationRoot)}
${environment("HOME", options.home ?? process.env.HOME ?? "")}
${environment("PATH", "/usr/local/bin:/usr/bin:/bin")}
${environment("KOJO_MANAGED_INSTALLATION", paths.installationRoot)}
${environment("KOJO_DAEMON_DATA", paths.dataRoot)}
${environment("KOJO_DAEMON_RUNTIME", paths.runtimeRoot)}
${environment("KOJO_DAEMON_CONFIG", paths.configurationRoot)}
${environment("KOJO_DAEMON_CACHE", paths.cacheRoot)}
UMask=0077
RuntimeDirectory=${managedDirectoryName}
RuntimeDirectoryMode=0700
RuntimeDirectoryPreserve=no
StateDirectory=${managedDirectoryName}
StateDirectoryMode=0700
CacheDirectory=${managedDirectoryName}
CacheDirectoryMode=0700
ConfigurationDirectory=${managedDirectoryName}
ConfigurationDirectoryMode=0700
Restart=on-failure
RestartSec=1s
TimeoutStopSec=30s
KillMode=control-group

[Install]
WantedBy=default.target
`;
};
