export type Issue64Tier = "U" | "I" | "H" | "B" | "R";

const tiers = (...values: ReadonlyArray<Issue64Tier>): ReadonlyArray<Issue64Tier> =>
  Object.freeze(values);

/** Immutable required tier allocation copied from issue #64, independent of evidence mappings. */
export const issue64RequiredTierAllocation = Object.freeze({
  "PKG-01": tiers("I"),
  "PKG-02": tiers("I"),
  "PKG-03": tiers("I"),
  "STATE-01": tiers("U", "I"),
  "STATE-02": tiers("I"),
  "STATE-03": tiers("U", "I"),
  "STATE-04": tiers("U", "I"),
  "GATE-01": tiers("U", "I"),
  "GATE-02": tiers("U", "I"),
  "RUNNER-01": tiers("I"),
  "RUNNER-02": tiers("I"),
  "RUNNER-03": tiers("U", "I"),
  "RUNNER-04": tiers("I"),
  "RECOVER-01": tiers("U", "I"),
  "RECOVER-02": tiers("U", "I"),
  "RECOVER-03": tiers("I"),
  "RECOVER-04": tiers("I", "H"),
  "RECOVER-05": tiers("I", "H"),
  "CANCEL-01": tiers("U", "I"),
  "CANCEL-02": tiers("I"),
  "REV-01": tiers("U", "I"),
  "REV-02": tiers("I"),
  "REV-03": tiers("I"),
  "REV-04": tiers("U", "I"),
  "REV-05": tiers("U", "I"),
  "SCHED-01": tiers("U"),
  "SCHED-02": tiers("I"),
  "SCHED-03": tiers("U", "I"),
  "SCHED-04": tiers("U", "I"),
  "PROJECT-01": tiers("U", "I"),
  "LOAD-01": tiers("I"),
  "LOAD-02": tiers("U", "I", "H"),
  "LIFE-01": tiers("H"),
  "LIFE-02": tiers("U", "I", "H"),
  "LIFE-03": tiers("I", "H"),
  "LIFE-04": tiers("I"),
  "LIFE-05": tiers("I"),
  "LIFE-06": tiers("I", "H"),
  "LIFE-07": tiers("I"),
  "LIFE-08": tiers("I", "H"),
  "ACCESS-01": tiers("I", "H"),
  "ACCESS-02": tiers("I"),
  "ACCESS-03": tiers("I"),
  "ACCESS-04": tiers("I", "B"),
  "CLIENT-01": tiers("I"),
  "CLIENT-02": tiers("U", "I"),
  "CLIENT-03": tiers("I"),
  "CLI-01": tiers("I"),
  "CLI-02": tiers("U", "I"),
  "UI-01": tiers("B"),
  "UI-02": tiers("B"),
  "UI-03": tiers("B"),
  "RELEASE-01": tiers("R", "H"),
  "RELEASE-02": tiers("R"),
  "RELEASE-03": tiers("R", "H"),
  "RELEASE-04": tiers("I", "R"),
} as const);

export type Issue64CheckId = keyof typeof issue64RequiredTierAllocation;
